name: financial_products
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management / DI
  flutter_riverpod: ^2.6.1

  # Adaptive UI
  screendapt: ^0.0.1-dev.2

  # Local data persistence
  sembast: ^3.7.2

  # Code generation for providers
  riverpod_annotation: ^2.6.1

  # Logging
  logger: ^2.4.0

  # Networking
  http: ^1.2.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11

  # Code generation for providers
  riverpod_generator: ^2.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400

  assets:
    - assets/images/
